In [1]:
# Importing the libraries

import pandas as pd
import numpy as np
import math as mt
import seaborn as sns #visualisation
import matplotlib.pyplot as plt # visualisation
plt.style.use("seaborn-whitegrid")
import warnings            
warnings.filterwarnings("ignore") # We can suppress the warnings
import statistics as stats #calculation

In [2]:
# Importing the dataset Production

df5 =pd.read_csv("5.Barley_Price.csv")
df6 =pd.read_csv("6.Meat_Cattle_Price.csv")
df7 =pd.read_csv("7.Meat_Pig_Price.csv")
df8 =pd.read_csv("8.Raw_Milk_Price.csv")

In [3]:
# change names on datasets

df5 = df5.rename(columns = {"Value":"Barley"})
df6 = df6.rename(columns = {"Value":"Meat Cattle"})
df7 = df7.rename(columns = {"Value":"Meat Pig"})
df8 = df8.rename(columns = {"Value":"Raw Milk"})

In [4]:
#Created a join tables
df_m3 = pd.merge(df5,df6, how='inner', on=["Area","Year"],suffixes=("_df5", "_df6"))
df_m4 = pd.merge(df7,df8, how='inner', on=["Area","Year"],suffixes=("_df7", "_df8"))
df_price = pd.merge(df_m3,df_m4, how='inner', on=["Area","Year"])

In [5]:
#full print
df_price

,Domain_Code_df5,Domain_df5,Area_Code_(M49)_df5,Area,Element_Code_df5,Element_df5,Item_Code_(CPC)_df5,Item_df5,Year_Code_df5,Year,...,Element_df8,Item_Code_(CPC)_df8,Item_df8,Year_Code_df8,Months_Code_df8,Months_df8,Unit_df8,Raw Milk,Flag_df8,Flag_Description_df8
0,PP,Producer Prices,40,Austria,5532,Producer Price (USD/tonne),115,Barley,2015,2015,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2015,7021,Annual value,USD,373.7,A,Official figure
1,PP,Producer Prices,40,Austria,5532,Producer Price (USD/tonne),115,Barley,2016,2016,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2016,7021,Annual value,USD,346.2,A,Official figure
2,PP,Producer Prices,40,Austria,5532,Producer Price (USD/tonne),115,Barley,2017,2017,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2017,7021,Annual value,USD,421.4,A,Official figure
3,PP,Producer Prices,40,Austria,5532,Producer Price (USD/tonne),115,Barley,2018,2018,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2018,7021,Annual value,USD,477.1,A,Official figure
4,PP,Producer Prices,40,Austria,5532,Producer Price (USD/tonne),115,Barley,2019,2019,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2019,7021,Annual value,USD,414.2,A,Official figure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),115,Barley,2016,2016,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2016,7021,Annual value,USD,331.7,A,Official figure
76,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),115,Barley,2017,2017,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2017,7021,Annual value,USD,360.1,A,Official figure
77,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),115,Barley,2018,2018,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2018,7021,Annual value,USD,366.2,A,Official figure
78,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),115,Barley,2019,2019,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2019,7021,Annual value,USD,350.6,A,Official figure
79,PP,Producer Prices,724,Spain,5532,Producer Price (USD/tonne),115,Barley,2020,2020,...,Producer Price (USD/tonne),2211,Raw milk of cattle,2020,7021,Annual value,USD,365.6,A,Official figure

In [6]:
# Clean the dataset, deleting useless columns for ou analyse

df_price.drop(["Domain_Code_df5","Domain_Code_df6","Domain_Code_df7","Domain_Code_df8"], axis=1, inplace=True)
df_price.drop(["Domain_df5","Domain_df6","Domain_df7","Domain_df8"], axis=1, inplace=True)
df_price.drop(["Area_Code_(M49)_df5","Area_Code_(M49)_df6","Area_Code_(M49)_df7","Area_Code_(M49)_df8"], axis=1, inplace=True)
df_price.drop(["Element_Code_df5","Element_Code_df6","Element_Code_df7","Element_Code_df8"], axis=1, inplace=True)
df_price.drop(["Element_df5","Element_df6","Element_df7","Element_df8"], axis=1, inplace=True)
df_price.drop(["Item_Code_(CPC)_df5","Item_Code_(CPC)_df6","Item_Code_(CPC)_df7","Item_Code_(CPC)_df8"], axis=1, inplace=True)
df_price.drop(["Item_df5","Item_df6","Item_df7","Item_df8"], axis=1, inplace=True)
df_price.drop(["Year_Code_df5","Year_Code_df6","Year_Code_df7","Year_Code_df8"], axis=1, inplace=True)
df_price.drop(["Months_Code_df5","Months_Code_df6","Months_Code_df7","Months_Code_df8"], axis=1, inplace=True)
df_price.drop(["Months_df5","Months_df6","Months_df7","Months_df8"], axis=1, inplace=True)
df_price.drop(["Unit_df5","Unit_df6","Unit_df7","Unit_df8"], axis=1, inplace=True)
df_price.drop(["Flag_df5","Flag_df6","Flag_df7","Flag_df8"], axis=1, inplace=True)
df_price.drop(["Flag_Description_df5","Flag_Description_df6","Flag_Description_df7","Flag_Description_df8"], axis=1, inplace=True)

# Prints out the first few rows
print(df_price.head())

      Area  Year  Barley  Meat Cattle  Meat Pig  Raw Milk
0  Austria  2015   130.9       4247.5    1597.0     373.7
1  Austria  2016   112.8       4137.2    1659.3     346.2
2  Austria  2017   131.0       4371.9    1875.3     421.4
3  Austria  2018   161.8       4582.1    1771.4     477.1
4  Austria  2019   137.7       4175.6    1981.5     414.2

In [7]:
#Save new data frame as extension.CSV
#df_price.to_csv("Consolidated Price.csv")